apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tripsplit
spec:
  parentRefs:
    - kind: Gateway
      name: nginx
      namespace: nginx-gateway
  hostnames:
    - trip-split.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: tripsplit
          port: 80