apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripsplit
  labels:
    app.kubernetes.io/name: tripsplit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tripsplit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tripsplit
    spec:
      containers:
      - name: trip-split
        image: docker.io/chudas/tripsplit:v0.2
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tripsplit
spec:
  selector:
    app.kubernetes.io/name: tripsplit
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: udp 
      protocol: UDP 
      port: 80
      targetPort: 3000
      